apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.allow-egress-to-backend-port-80
  namespace: frontend
spec:
  selector: all() 
  egress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: 'projectcalico.org/name == "backend"'
        ports:
          - 80
          - 8000