apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-egress-external-postgres-db
  namespace: backend
spec:
  selector: all()
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        nets:
          - 192.168.68.101/32
        # port:
        #   - 5432