apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default.same-allow-namespace-database-client
  namespace: database
spec:
  selector: all()
  ingress:
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: 'projectcalico.org/name == "database"'
      destination:
        ports:
          - 5432
  egress:
  - action: Allow
    protocol: TCP
    destination:
      namespaceSelector: 'projectcalico.org/name == "database"'
      ports:
        - 5432