apiVersion: v1
kind: Service
metadata:
  name: mushroom-api-svc
spec:
  selector:
    app.kubernetes.io/name: mushroom-api
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8000
    targetPort: 8000