apiVersion: v1
kind: Service
metadata:
  name: mushroom-api-service
  namespace: backend
  labels:
    app: mushroom-api
spec:
  type: ClusterIp
  selector:
    app: mushroom-api
  ports:
    - protocol: TCP
      port: 8000       # Porta que será acessada externamente
      targetPort: 8000 # Porta no container
