apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80