apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-class-name
  volumeMode: Filesystem