kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  podSubnet: '192.168.0.0/16'
  apiServerPort: 6443
  disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
- role: worker