apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: blue
  labels:
    app.kubernetes.io/name: app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-blue
  template:
    metadata:
      labels:
        app: app-blue
    spec:
      containers:
      - name: app-blue
        image: nginx
        ports:
        - containerPort: 80