apiVersion: v1
kind: Service
metadata:
  name: app-blue
  namespace: blue
  labels:
    app: app-blue
spec:
  type: ClusterIP
  selector:
    app: app-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80